/*
BEGIN   END STATEMENT

DECLARE -->DECLEARATION STATEMENTS


BEGIN
	PRINT' WELCOME TO T-SQL';
END

VARIABLES  IN DATABASE TYPE

@NAME		INT;
@VAR		VARCHAR(23);
2QUANTITY		NUMERIC;
DECLEAR @NAME VARCHAR(15) = 'ASMA'; 

*/
BEGIN
	PRINT' WELCOME TO T-SQL';
	DECLARE @VAR1 INT = 5;
	DECLARE @VAR2 INT ;
	SET @VAR2 =5
	PRINT @VAR1;
END

BEGIN
	DECLARE @NAME VARCHAR(20);
	DECLARE @SAL NUMERIC(8,2);
	SET @NAME = 'ALI';
	SET @SAL = 700;
	PRINT @NAME;
	PRINT @SAL;
	PRINT @NAME +' ' +CAST( @SAL AS VARCHAR); -- CAST TO CONVERT THE DATA TYPE 
END

BEGIN 
	DECLARE @WID NUMERIC(8,2);
	DECLARE @HIG NUMERIC(8,2);
	DECLARE @AREA NUMERIC(8,2);
	SET @HIG = 22;
	SET @WID = 44;
	SET @AREA = @WID * @HIG;
	PRINT 'THIS AREA IS = ' + CAST( @AREA AS VARCHAR);
END

BEGIN
	DECLARE @FIRST_NAME VARCHAR(20);
	DECLARE @LAST_NAME VARCHAR(20);

	SELECT @FIRST_NAME=FirstName, @LAST_NAME=LastName
	FROM Customer
	WHERE Id = 4;

	PRINT 'CUSTOMER WITH ID = 4 : ' + @FIRST_NAME + ' '+ @LAST_NAME;
END
